services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude:
      - '../src/Application/DependencyInjection/'
      - '../src/*/{Exception,Entity,Value}/'
      - '../src/Kernel.php'

  # Infrastructure services

  App\Infrastructure\Service\Provider\ExchangeRatesApiProvider:
    arguments:
      $accessKey: '%env(EXCHANGE_RATES_API_KEY)%'

  App\Domain\Repository\TransactionRepositoryInterface: '@App\Infrastructure\Repository\MockedTransactionRepository'
  App\Domain\Service\Provider\CountryCodeProviderInterface: '@App\Infrastructure\Service\Provider\BinListCountryCodeProvider'
  App\Domain\Service\Provider\CurrencyRateProviderInterface: '@App\Infrastructure\Service\Provider\ExchangeRatesApiProvider'
